apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: weather-external-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: weather-secret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: weather-api-key
    remoteRef:
      key: weather-api-key