apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-app
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-app
      port: 80
      