---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix

spec:
  stripPrefix:
    prefixes:
      - /weather-app


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-app
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/weather-app`)
    kind: Rule
    services:
    - name: weather-app
      port: 80
    middlewares:
    - name: stripprefix
      