apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`clusters.dev-denny.cloudns.be`) && PathPrefix(`/hello`)
    kind: Rule
    services:
    - name: hello
      port: 80
  tls:
    certResolver: myresolver