apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/hello`)
    kind: Rule
    services:
    - name: hello
      port: 80
      